formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys a ClickHouse database on Kubernetes. It uses the official ClickHouse Helm chart to set up a reliable columnar database instance, suitable for high-performance analytics and data warehousing in the cluster. The module also provides outputs for easy access to database connection details.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
