formatter: "markdown table"

content: |-
  {{ .Header }}
  {{ include "../../doc_site/docs/source/partials/status_development.md" }}

  ## Overview

  This module deploys Windmill, an open-source developer platform for creating, sharing, and running scripts and workflows, on Kubernetes. It sets up the Windmill server and its required components using a Helm chart. The module configures the necessary resources for running scripts and workflows, and exposes the Windmill UI for easy management and execution of tasks.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
