formatter: "markdown table"

content: |-
  {{ .Header }}

  Relativistic is a Terraform, Helm, and custom configuration project to be able to deploy an production grade open source data stack quickly.

  ## Examples



  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}


sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
