formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This is the root module for the Relativistic project, which orchestrates the deployment of various data engineering and analytics tools on Kubernetes. It includes submodules for Airbyte, Airflow, Argo CD, Argo Workflows, Dagster, Kubernetes Dashboard, Lightdash, Prometheus, Superset, and more. This module provides a comprehensive data platform setup for modern data stack requirements.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
