formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys Apache Airflow, a platform to programmatically author, schedule, and monitor workflows, on Kubernetes. It sets up the Airflow webserver, scheduler, and workers using a Helm chart. The module also configures persistent storage and exposes the Airflow UI.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
