dags:
  gitSync:
    branch: main
    depth: 1
    enabled: true
    httpSecret: ""
    httpSecretPasswordKey: password
    httpSecretUsernameKey: username
    image:
      gid: 65533
      pullPolicy: IfNotPresent
      repository: registry.k8s.io/git-sync/git-sync
      tag: v3.6.5
      uid: 65533
    maxFailures: 0
    repo: https://github.com/kadreio/jaffle-shop-classic.git
    repoSubPath: "dags"
    resources: {}
    revision: HEAD
    sshKnownHosts: ""
    sshSecret: ""
    sshSecretKey: id_rsa
    subPath: ""
    submodules: recursive
    syncTimeout: 120
    syncWait: 60
  initContainer:
    enabled: true
  installRequirements: true
  path: /opt/airflow/dags
  persistence:
    accessMode: ReadOnlyMany
    enabled: false
    existingClaim: ""
    size: 1Gi
    storageClass: ""
    subPath: ""
