formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys Prometheus, an open-source systems monitoring and alerting toolkit, on Kubernetes. It sets up the Prometheus server, Alertmanager, and various exporters using the kube-prometheus-stack Helm chart. The module also deploys Loki for log aggregation, providing a comprehensive monitoring and logging solution for the cluster.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
