formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys a PostgreSQL database specifically for analytics purposes on Kubernetes. It uses the Bitnami PostgreSQL Helm chart to set up a robust and scalable database instance, suitable for storing and querying large datasets in analytics workflows.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
