formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes. It sets up the necessary Helm release, configures SSO integration, and exposes the Argo CD server. The module includes OAuth2 configuration for secure access.

  ```{tip}
    This implementation uses the official Argo CD Helm chart. You can find more details in the [Argo CD documentation](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd).

    Helm values have been customized from the defaults, and common configuration needs are exposed as variables.

    If needed the entire helm chart can be customized by setting the `override_helm_values` variable.
  ```

  ## Compute Requirements

  For optimal performance, the following resources are recommended:
  - 1 CPU core
  - 3GB of memory

  Argo CD is relatively lightweight compared to other tools, but resource requirements may increase with the number of applications and repositories being managed.

  ```{warning}
    When using SSO with Google OAuth, make sure to configure the correct redirect URIs in your Google Cloud Console. The redirect URI should be `https://your-domain/api/dex/callback`.
  ```

  ## Local Deployment

  Argo CD will start on port 30088 by default.

  ## Production Considerations

  Argo CD is licensed under the Apache License 2.0, making it suitable for both personal and commercial use.

  It has a built in "Dex" server for OAuth2 authentication. Google OAuth is supported out of the box via variables, other providers can be added by passing in a custom `override_helm_values` variable.

  ## Examples

  {{ include "../../doc_site/docs/source/partials/example_note.md" }}

  #### Simple
  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true 