formatter: "markdown table"

content: |-
  {{ .Header }}

  ## Overview

  This module deploys Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes. It sets up the Argo CD server, repo server, and application controller using a Helm chart. The module also configures SSO integration and exposes the Argo CD UI.

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
