global:
  domain: argocd.data.kadre.io
configs:
  cm:
    create: true
    dex.config: |
      enablePasswordDB: true

      connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: "${google_oauth_client_id}"
          clientSecret: "${google_oauth_client_secret}"
    url: ${deployed_url}

  params:
    server.insecure: true
server:
  podLabels: {
    app: argo_webserver
  }
