global:
  domain: ${target_domain}
configs:
  rbac:
    create: true
    policy.default: 'role:admin'
    
  cm:
    create: true
    dex.config: |
      connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID: "${google_oauth_client_id}"
          clientSecret: "${google_oauth_client_secret}"

    url: https://${target_domain}

  params:
    server.insecure: true
server:
  podLabels: {
    app: argo_webserver
  }
