formatter: "markdown table"

content: |-
  {{ .Header }}
  
  {{ include "../../doc_site/docs/source/partials/status_beta.md" }}

  ## Overview

  This module deploys Apache Superset, a modern data exploration and visualization platform, on Kubernetes. It sets up the Superset web application, its dependencies, and the necessary database using a Helm chart. The module also configures authentication and exposes the Superset UI for easy access to data analytics and dashboard creation.

  ## Compute Nodes

  For optimal performance, the following resources are recommended:
  - 1 or more CPU cores
  - At least 2GB of memory

  ## Local Deployment

  Superset will start on port 30086 by default.

  ## Production Considerations

  Superset is licensed under the Apache License 2.0.


  ```{Warning}
    Superset will deploy a self-hosted version of Postgres. This will not back iteslf up, and is not HA. For many use cases, this is not a problem, as Superset is not a system of record itself, and can easily be recreated in disaster recovery. External postgres can be configured by helm chart overrides., but future work will simplify passing in an existing postgres instance.  
  ```
  ## Examples

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}



sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
