name: E2E Tests

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Kubernetes
      uses: engineerd/setup-kind@v0.5.0
        with: 
          version: "v0.11.1"

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run E2E tests
      run: |
        go test -v ./test

    - name: Clean up
      if: always()
      run: |
        kind delete cluster
